USE [master]
GO

/****** Object:  Database [dbWeelo]    Script Date: 12/21/2021 8:28:36 PM ******/
CREATE DATABASE [dbWeelo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dbWeelo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbWeelo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dbWeelo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dbWeelo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dbWeelo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dbWeelo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dbWeelo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dbWeelo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dbWeelo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dbWeelo] SET ARITHABORT OFF 
GO

ALTER DATABASE [dbWeelo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dbWeelo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dbWeelo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dbWeelo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dbWeelo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dbWeelo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dbWeelo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dbWeelo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dbWeelo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dbWeelo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dbWeelo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dbWeelo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dbWeelo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dbWeelo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dbWeelo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dbWeelo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dbWeelo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dbWeelo] SET RECOVERY FULL 
GO

ALTER DATABASE [dbWeelo] SET  MULTI_USER 
GO

ALTER DATABASE [dbWeelo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dbWeelo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dbWeelo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dbWeelo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dbWeelo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dbWeelo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [dbWeelo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dbWeelo] SET  READ_WRITE 
GO


